{
 "title": "Jenkins 构建大盘",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jenkins 正在构建的 Jobs 及 耗时",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(time() * 1000 - avg(jenkins_job_building{job_name != ''}) by (job_name, node, number, url, user))",
     "legendFormat": "{{ user }} -> [ {{ job_name }} ]"
    }
   ]
  },
  {
   "title": "Jenkins 构建历史及耗时（3 小时内）",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jenkins_job_build_result{building=\"False\", in_3hours=\"True\"}",
     "legendFormat": " {{job_name}}  <<< {{user}} - {{ duration }} "
    }
   ]
  },
  {
   "title": "Jenkins 构建历史（Top 50）",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jenkins_job_build_duration{building=\"False\"}"
    }
   ]
  }
 ]
}